#!/bin/sh

# Build this project from Akefile using ake, first installing ake if
# necessary.

# You may want to configure CFLAGS.
# export CFLAGS='-g2 -Wall -W'

if [ -x ake ]
then
    awk -f ake "$@"
else
    curl 'https://raw.github.com/darius/ake/master/ake' -o ake &&
    chmod +x ake &&
    echo ""
    echo "Had to download ake; rerun $0 now to use it."
    echo "(For security you're getting a chance to view the download before"
    echo "running it.)"
    exit 1
fi

